services:
  localstack:
    image: localstack/localstack:1.4.0
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs,
      - DEBUG=1,
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./.localstack/create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh
    healthcheck:
      test: awslocal sqs get-queue-url --queue-name bolid--logger
        && awslocal sqs get-queue-url --queue-name bolid--monitor
        && awslocal sqs get-queue-url --queue-name bolid--master
        && awslocal sqs get-queue-url --queue-name master--bolid

      interval: 5s
      timeout: 10s
      start_period: 10s
